#========================================================================
#
# Makefile.config
#
# Miscellaneous configuration, to be included in all makefiles.
#
#========================================================================

#------------------------------------------------------------------------
#
# Before compiling, read through this file and select the options
# appropriate to your system.
#
# Eventually, this will be done by an automated script.  If you have to
# make any changes for your system, please send them to me
# (derekn@ece.cmu.edu).
#
# The following special options can be used by adding the appropriate
# flag(s) to CFLAGS2.
#
# -DNO_POPEN   Don't use the popen() function to run uncompress.
#              Instead, uncompress the file on disk and then fopen() the
#              uncompressed file.  This is useful for non-UNIX operating
#              systems which don't have a popen function.
#
# -DUSE_GZIP   Use "gzip -d" (equivalent to gunzip) instead of
#              uncompress.  This is useful for systems without
#              uncompress or where gzip is faster than uncompress.
#
# -DNO_XPM     Don't call libXpm (pixmap) functions.  You'll also need to
#              change the XPMLIB variable below.
#
#------------------------------------------------------------------------

#------------------------------------------------------------------------
# Shell.
#------------------------------------------------------------------------

# Necessary for OS/2.
#SHELL = sh

#------------------------------------------------------------------------
# Installation directory.
#------------------------------------------------------------------------

# Binaries and man pages will be installed here:
PREFIX = /usr/local

# SCO puts stuff here:
#PREFIX = /u

# For OS/2:
#PREFIX = $(X11ROOT)/xfree86

#------------------------------------------------------------------------
# C compiler.
#------------------------------------------------------------------------

# You can use the GNU C compiler:
CC = gcc

# Or use your system's default C compiler:
#CC = cc

# HP-UX with HP compilers:
#CC = cc -Aa -D_HPUX_SOURCE

#------------------------------------------------------------------------
# C++ compiler.
#------------------------------------------------------------------------

# Use the GNU C++ compiler.  Gcc is used instead of g++: gcc recognizes
# C++ files (by their .cc extension) and has the advantage of not linking
# with libg++ which causes problems on some systems (Solaris, Linux-ELF).
CXX = gcc

# Use g++.  There shouldn't be any reason to use this.
#CXX = g++

# Or use your system's default C++ compiler:
#CXX = CC

# The Digital Unix C++ compiler:
#CXX = cxx

#------------------------------------------------------------------------
# Library archiver and indexer.
#------------------------------------------------------------------------

# These flags should work for most systems:
AR = ar rc

# For OS/2:
#AR = ar -rc

# For most systems, use ranlib:
RANLIB = ranlib

# Solaris 2.x, HP-UX, SCO Unix, SINIX, and UXP/DS (Fujitsu) don't need a
# ranlib:
#RANLIB = true

# For OS/2:
#RANLIB = ar -s

#------------------------------------------------------------------------
# Binary stripper.
#------------------------------------------------------------------------

# For smaller binaries:
STRIP = strip

# To keep debugging info:
# (and for OS/2 which doesn't use strip)
#STRIP = true

#------------------------------------------------------------------------
# Installer.
#------------------------------------------------------------------------

# This should work for most systems:
INSTALL = install -c

# For Digital Unix, use the BSD-install-compatible script:
#INSTALL = install.sh -c

# For systems without install:
#INSTALL = cp

#------------------------------------------------------------------------
# Executable and library file name conventions.
#------------------------------------------------------------------------

# For Unix systems:
LIBPREFIX = lib
EXE =

# For OS/2:
#LIBPREFIX =
#EXE = .exe

#------------------------------------------------------------------------
# Extra flags for the C compiler.
# This can include things like -I and -L if your include files or
# libraries are in non-standard places.
#------------------------------------------------------------------------

# This will work for most systems:
#CFLAGS2 = -O2 -Wall -DNO_XPM

# If you're using g++ 2.7.x, you'll want to use -Wno-unused:
CFLAGS2 = -O2 -Wall -Wno-unused -DNO_XPM

# For Linux/FreeBSD/NetBSD/BSDI systems using XFree86:
#CFLAGS2 = -O2 -Wall -I/usr/X11R6/include -Wno-unused

# For official FreeBSD port (using the FreeBSD makefiles):
#CFLAGS2 = -O2 -Wall -I$(X11BASE)/include -Wno-unused -DNO_XPM

# For Solaris:
#CFLAGS2 = -O2 -Wall -I/usr/openwin/include -DNO_XPM

# For Digital Unix with vendor compilers:
#CFLAGS2 = -O2 -Olimit 1000 -DNO_XPM

# For HP-UX:
#CFLAGS2 = -O -I/usr/include/X11R5 -DNO_XPM

# For SINIX cc/CC:
#CFLAGS2 = -O -v -DNO_XPM

# For QNX with Watcom compilers:
#CFLAGS2 = -O2 -wx -DUSE_GZIP -DNO_XPM

# For SCO Unix with SCO SDK:
#CFLAGS2 = -belf -DNO_XPM

# For OS/2:
#CFLAGS2 = -O2 -Wall -Wno-unused -Zmtd -Zsysv-signals -D__ST_MT_ERRNO -Zbin-files

# For debugging:
#CFLAGS2 = -g -O -Wall -DDEBUG_MEM
#CFLAGS2 = -g -pg -O -Wall -DDEBUG_MEM

#------------------------------------------------------------------------
# Extra flags for the C++ compiler.
#------------------------------------------------------------------------

# This is generally the same as CFLAGS2:
CXXFLAGS2 = $(CFLAGS2)

# For SCO Unix with SCO SDK:
#CXXFLAGS2 = $(CFLAGS2) +.cc

#------------------------------------------------------------------------
# Any flags necessary to link in libX11.
#------------------------------------------------------------------------

# For most systems, just grab the X library:
XLIBS = -lX11

# For Linux/FreeBSD/NetBSD/BSDI systems using XFree86:
#XLIBS = -L/usr/X11R6/lib -lX11

# For official FreeBSD port (using the FreeBSD makefiles):
#XLIBS = -L$(X11BASE)/lib -lX11

# Some BSDI systems may need -lipc (?):
#XLIBS = -L/usr/X11R6/lib -lX11 -lipc

# For Solaris:
#XLIBS = -L/usr/openwin/lib -lX11 -lnsl -lsocket

# For UnixWare, SINIX, and probably other SysV-ish Unixes:
#XLIBS = -lX11 -lnsl -lsocket

# For SCO Unix:
#XLIBS = -lX11_s -lsocket -lmalloc -lintl
#XLIBS = -lX11 -lsocket

# For some old Ultrix systems and maybe others, pick up a newer
# X library:
#XLIBS = -lX11-mit

# For HP-UX:
#XLIBS = -L/usr/lib/X11R5 -lX11

# For RISC/os (MIPS):
#XLIBS = -L/usr/X11/lib -lX11 -lbsd -lsun

# For QNX:
#XLIBS = -L/usr/lib/X11 -lX11_s -lXqnx_s -lsocket

# For Evans & Sutherland ESV, ES/OS:
#XLIBS = -lX11 -lbsd

# For OS/2:
#XLIBS = -L$(X11ROOT)/xfree86/lib -lX11 -lm -lbsd -lsocket /emx/lib/binmode.o

#------------------------------------------------------------------------
# Xpm (pixmap) library.
#------------------------------------------------------------------------

# This is needed for the color icon:
#XPMLIB = -lXpm

# Use this if you don't have libXpm (and also define NO_XPM in CFLAGS2):
XPMLIB =

#------------------------------------------------------------------------
# C++ compilation rule.
# Different versions of make have different C++ rules.  This rule makes
# everything consistent.
#------------------------------------------------------------------------

.SUFFIXES: .cc

# For almost all systems:
.cc.o:
	$(CXX) $(CXXFLAGS) -c $<

# If your C++ compiler wants foo.C instead of foo.cc, use this:
#.cc.o:
#	cp $< $*.C
#	$(CXX) $(CXXFLAGS) -c $*.C
#	rm $*.C
