#========================================================================
#
# LTK library Makefile
#
# Copyright 1996 Derek B. Noonburg
#
#========================================================================

include ../Makefile.config

GOODIR = ../goo

CXXFLAGS = $(CXXFLAGS2) -I$(GOODIR) -I.

all: $(LIBPREFIX)LTK.a ltkbuild

#------------------------------------------------------------------------

LTK_OBJS =	LTKApp.o \
		LTKBorder.o \
		LTKBox.o \
		LTKButton.o \
		LTKButtonDialog.o \
		LTKCanvas.o \
		LTKCompoundWidget.o \
		LTKDblBufCanvas.o \
		LTKEmpty.o \
		LTKFileReq.o \
		LTKLabel.o \
		LTKList.o \
		LTKMenu.o \
		LTKMisc.o \
		LTKResources.o \
		LTKScrollbar.o \
		LTKScrollingCanvas.o \
		LTKTextIn.o \
		LTKWidget.o \
		LTKWindow.o

$(LIBPREFIX)LTK.a: $(LTK_OBJS)
	rm -f $(LIBPREFIX)LTK.a
	$(AR) $(LIBPREFIX)LTK.a $(LTK_OBJS)
	$(RANLIB) $(LIBPREFIX)LTK.a

#------------------------------------------------------------------------

LTKBUILD_OBJS = ltkbuild.o
LTKBUILD_LIBS = -L$(GOODIR) -lGoo

ltkbuild: $(LTKBUILD_OBJS)
	$(CXX) $(CXXFLAGS) -o ltkbuild $(LTKBUILD_OBJS) $(LTKBUILD_LIBS)

#------------------------------------------------------------------------

clean:
	rm -f $(LTK_OBJS) $(LIBPREFIX)LTK.a
	rm -f $(LTKBUILD_OBJS) ltkbuild
	rm -f Makefile.bak

#------------------------------------------------------------------------

depend:
	cp Makefile Makefile.bak
	sed '/^#----- dependences -----/q' Makefile.bak >Makefile
	echo >>Makefile
	$(CXX) $(CXXFLAGS) -M $(LTK_OBJS:.o=.cc) |\
	  sed 's/\/usr\/[^ ]* *//g;/^  \\$$/d' |\
	  grep -v '^ \\$$' >>Makefile
	$(CXX) $(CXXFLAGS) -M $(LTKBUILD_OBJS:.o=.cc) |\
	  sed 's/\/usr\/[^ ]* *//g;/^  \\$$/d' |\
	  grep -v '^ \\$$' >>Makefile

#----- dependences -----

LTKApp.o: LTKApp.cc \
 ../goo/gtypes.h LTKApp.h \
 ../goo/GString.h LTKResources.h LTKWindow.h \
 LTKMenu.h LTKMisc.h LTKWidget.h
LTKBorder.o: LTKBorder.cc \
 ../goo/gtypes.h \
 LTKBorder.h
LTKBox.o: LTKBox.cc \
 LTKWindow.h ../goo/gtypes.h \
 ../goo/GString.h LTKBox.h LTKBorder.h \
 LTKWidget.h
LTKButton.o: LTKButton.cc \
 LTKWindow.h ../goo/gtypes.h \
 ../goo/GString.h LTKButton.h LTKWidget.h \
 LTKBorder.h
LTKButtonDialog.o: LTKButtonDialog.cc \
 LTKApp.h \
 ../goo/gtypes.h ../goo/GString.h LTKLabel.h \
 LTKWidget.h LTKWindow.h LTKButton.h LTKEmpty.h LTKBox.h LTKBorder.h \
 LTKButtonDialog.h LTKCompoundWidget.h
LTKCanvas.o: LTKCanvas.cc \
 LTKWindow.h ../goo/gtypes.h \
 ../goo/GString.h LTKCanvas.h LTKWidget.h
LTKCompoundWidget.o: LTKCompoundWidget.cc \
 LTKApp.h \
 ../goo/gtypes.h ../goo/GString.h \
 LTKWindow.h LTKBox.h LTKBorder.h LTKWidget.h \
 LTKCompoundWidget.h
LTKDblBufCanvas.o: LTKDblBufCanvas.cc \
 LTKWindow.h ../goo/gtypes.h \
 ../goo/GString.h LTKDblBufCanvas.h LTKWidget.h
LTKEmpty.o: LTKEmpty.cc \
 LTKWindow.h ../goo/gtypes.h \
 ../goo/GString.h LTKEmpty.h LTKWidget.h
LTKFileReq.o: LTKFileReq.cc \
 ../goo/GString.h \
 ../goo/gfile.h \
 ../goo/gtypes.h \
 LTKBox.h LTKBorder.h LTKWidget.h LTKWindow.h LTKLabel.h LTKList.h \
 LTKScrollbar.h LTKTextIn.h LTKEmpty.h LTKFileReq.h \
 LTKCompoundWidget.h
LTKLabel.o: LTKLabel.cc \
 LTKLabel.h ../goo/GString.h \
 LTKWidget.h ../goo/gtypes.h LTKWindow.h
LTKList.o: LTKList.cc \
 ../goo/gmem.h \
 LTKList.h ../goo/GString.h \
 LTKWidget.h ../goo/gtypes.h LTKWindow.h
LTKMenu.o: LTKMenu.cc \
 ../goo/gmem.h \
 LTKConfig.h LTKApp.h \
 ../goo/gtypes.h ../goo/GString.h \
 LTKWindow.h LTKBorder.h LTKMenu.h
LTKMisc.o: LTKMisc.cc \
 LTKMisc.h \
 ../goo/GString.h LTKWindow.h \
 ../goo/gtypes.h LTKWidget.h
LTKResources.o: LTKResources.cc \
 ../goo/gtypes.h ../goo/GString.h ../goo/gfile.h \
 LTKConfig.h \
 LTKMisc.h LTKResources.h
LTKScrollbar.o: LTKScrollbar.cc \
 LTKApp.h \
 ../goo/gtypes.h ../goo/GString.h \
 LTKWindow.h LTKScrollbar.h LTKWidget.h \
 LTKBorder.h
LTKScrollingCanvas.o: LTKScrollingCanvas.cc \
 LTKWindow.h ../goo/gtypes.h \
 ../goo/GString.h LTKScrollingCanvas.h \
 LTKWidget.h
LTKTextIn.o: LTKTextIn.cc \
 ../goo/gtypes.h ../goo/GString.h \
 LTKWindow.h LTKTextIn.h LTKWidget.h LTKBorder.h
LTKWidget.o: LTKWidget.cc \
 LTKWindow.h ../goo/gtypes.h \
 ../goo/GString.h LTKWidget.h
LTKWindow.o: LTKWindow.cc \
 LTKConfig.h LTKApp.h \
 ../goo/gtypes.h ../goo/GString.h \
 LTKMenu.h LTKWindow.h LTKWidget.h LTKBox.h LTKBorder.h
