LTKApp.o: LTKApp.cc \
 ../goo/gtypes.h LTKApp.h \
 ../goo/GString.h LTKResources.h LTKWindow.h LTKMenu.h LTKMisc.h \
 LTKWidget.h
LTKBorder.o: LTKBorder.cc \
 ../goo/gtypes.h \
 LTKBorder.h
LTKBox.o: LTKBox.cc \
 LTKWindow.h ../goo/gtypes.h \
 ../goo/GString.h LTKBox.h LTKBorder.h \
 LTKWidget.h
LTKButton.o: LTKButton.cc \
 LTKWindow.h ../goo/gtypes.h \
 ../goo/GString.h LTKButton.h LTKWidget.h \
 LTKBorder.h
LTKButtonDialog.o: LTKButtonDialog.cc \
 LTKApp.h \
 ../goo/gtypes.h ../goo/GString.h LTKLabel.h \
 LTKWidget.h LTKWindow.h LTKButton.h LTKEmpty.h LTKBox.h LTKBorder.h \
 LTKButtonDialog.h LTKCompoundWidget.h
LTKCanvas.o: LTKCanvas.cc \
 LTKWindow.h ../goo/gtypes.h \
 ../goo/GString.h LTKCanvas.h LTKWidget.h
LTKCompoundWidget.o: LTKCompoundWidget.cc \
 LTKApp.h \
 ../goo/gtypes.h ../goo/GString.h \
 LTKWindow.h LTKBox.h LTKBorder.h LTKWidget.h \
 LTKCompoundWidget.h
LTKDblBufCanvas.o: LTKDblBufCanvas.cc \
 LTKWindow.h ../goo/gtypes.h \
 ../goo/GString.h LTKDblBufCanvas.h LTKWidget.h
LTKEmpty.o: LTKEmpty.cc \
 LTKWindow.h ../goo/gtypes.h \
 ../goo/GString.h LTKEmpty.h LTKWidget.h
LTKFileReq.o: LTKFileReq.cc \
 ../goo/GString.h \
 ../goo/gfile.h \
 ../goo/gtypes.h \
 LTKBox.h LTKBorder.h LTKWidget.h LTKWindow.h LTKLabel.h LTKList.h \
 LTKScrollbar.h LTKTextIn.h LTKEmpty.h LTKFileReq.h \
 LTKCompoundWidget.h
LTKLabel.o: LTKLabel.cc \
 LTKLabel.h ../goo/GString.h \
 LTKWidget.h ../goo/gtypes.h LTKWindow.h
LTKList.o: LTKList.cc \
 ../goo/gmem.h \
 LTKList.h ../goo/GString.h \
 LTKWidget.h ../goo/gtypes.h LTKWindow.h
LTKMenu.o: LTKMenu.cc \
 ../goo/gmem.h \
 LTKConfig.h LTKApp.h \
 ../goo/gtypes.h ../goo/GString.h \
 LTKWindow.h LTKBorder.h LTKMenu.h
LTKMisc.o: LTKMisc.cc \
 LTKMisc.h \
 ../goo/GString.h LTKWindow.h \
 ../goo/gtypes.h LTKWidget.h
LTKResources.o: LTKResources.cc \
 ../goo/gtypes.h ../goo/GString.h ../goo/gfile.h \
 LTKConfig.h \
 LTKMisc.h LTKResources.h
LTKScrollbar.o: LTKScrollbar.cc \
 LTKApp.h \
 ../goo/gtypes.h ../goo/GString.h \
 LTKWindow.h LTKScrollbar.h LTKWidget.h \
 LTKBorder.h
LTKScrollingCanvas.o: LTKScrollingCanvas.cc \
 LTKWindow.h ../goo/gtypes.h \
 ../goo/GString.h LTKScrollingCanvas.h \
 LTKWidget.h
LTKTextIn.o: LTKTextIn.cc \
 ../goo/gtypes.h ../goo/GString.h \
 LTKWindow.h LTKTextIn.h LTKWidget.h LTKBorder.h
LTKWidget.o: LTKWidget.cc \
 LTKApp.h \
 ../goo/gtypes.h ../goo/GString.h \
 LTKWindow.h LTKWidget.h
LTKWindow.o: LTKWindow.cc \
 LTKConfig.h LTKApp.h \
 ../goo/gtypes.h ../goo/GString.h \
 LTKMenu.h LTKWindow.h LTKWidget.h LTKBox.h LTKBorder.h
ltkbuild.o: ltkbuild.cc \
 ../goo/gtypes.h \
 ../goo/gmem.h ../goo/GString.h ltkbuild-widgets.h
