Array.o: Array.cc \
 ../goo/gmem.h \
 Object.h \
 ../goo/gtypes.h ../goo/GString.h Array.h Dict.h Stream.h
Catalog.o: Catalog.cc \
 ../goo/gmem.h \
 Object.h \
 ../goo/gtypes.h ../goo/GString.h Array.h Dict.h \
 Stream.h Page.h Error.h Link.h Catalog.h
Dict.o: Dict.cc \
 ../goo/gmem.h \
 Object.h \
 ../goo/gtypes.h ../goo/GString.h Array.h Dict.h Stream.h XRef.h
Error.o: Error.cc \
 ../goo/gtypes.h \
 Params.h Error.h
Gfx.o: Gfx.cc \
 ../goo/gmem.h Object.h ../goo/gtypes.h \
 ../goo/GString.h Array.h Dict.h Stream.h Lexer.h Parser.h GfxFont.h \
 GfxState.h OutputDev.h Params.h Error.h Gfx.h
GfxFont.o: GfxFont.cc \
 ../goo/GString.h ../goo/gmem.h ../goo/gfile.h \
 ../goo/gtypes.h config.h Object.h Array.h \
 Dict.h Stream.h Error.h Params.h GfxFont.h FontInfo.h
GfxState.o: GfxState.cc \
 ../goo/gmem.h \
 Object.h \
 ../goo/gtypes.h ../goo/GString.h Array.h Dict.h Stream.h GfxState.h
Lexer.o: Lexer.cc \
 Lexer.h Object.h \
 ../goo/gtypes.h ../goo/gmem.h \
 ../goo/GString.h Array.h Dict.h Stream.h Error.h
Link.o: Link.cc \
 ../goo/gmem.h \
 ../goo/GString.h \
 Error.h Object.h ../goo/gtypes.h Array.h Dict.h Stream.h Link.h
Object.o: Object.cc \
 Object.h \
 ../goo/gtypes.h ../goo/gmem.h ../goo/GString.h Array.h Dict.h \
 Stream.h Error.h XRef.h
OutputDev.o: OutputDev.cc \
 Object.h \
 ../goo/gtypes.h ../goo/gmem.h ../goo/GString.h Array.h Dict.h \
 Stream.h GfxState.h OutputDev.h
Page.o: Page.cc \
 Object.h \
 ../goo/gtypes.h \
 ../goo/gmem.h ../goo/GString.h Array.h Dict.h Stream.h XRef.h \
 OutputDev.h Gfx.h Error.h Params.h Page.h
Params.o: Params.cc \
 ../goo/gtypes.h ../goo/gmem.h ../goo/GString.h ../goo/gfile.h \
 Params.h
Parser.o: Parser.cc \
 Object.h \
 ../goo/gtypes.h ../goo/gmem.h ../goo/GString.h Array.h Dict.h \
 Stream.h Parser.h Lexer.h Error.h
PDFDoc.o: PDFDoc.cc \
 ../goo/GString.h config.h Page.h Object.h ../goo/gtypes.h \
 ../goo/gmem.h Array.h Dict.h Stream.h Catalog.h XRef.h Link.h \
 OutputDev.h Params.h Error.h PDFDoc.h
PSOutputDev.o: PSOutputDev.cc \
 ../goo/GString.h \
 config.h Object.h ../goo/gtypes.h ../goo/gmem.h Array.h Dict.h \
 Stream.h Error.h GfxState.h GfxFont.h Catalog.h Page.h PSOutputDev.h \
 OutputDev.h
Stream.o: Stream.cc \
 ../goo/gmem.h config.h \
 Error.h Object.h ../goo/gtypes.h ../goo/GString.h Array.h Dict.h \
 Stream.h Stream-CCITT.h
TextOutputDev.o: TextOutputDev.cc \
 ../goo/GString.h ../goo/gmem.h config.h Error.h \
 GfxState.h ../goo/gtypes.h GfxFont.h Object.h Array.h Dict.h Stream.h \
 TextOutputDev.h OutputDev.h TextOutputFontInfo.h
XOutputDev.o: XOutputDev.cc \
 ../goo/gmem.h \
 ../goo/GString.h ../ltk/LTKWindow.h \
 ../goo/gtypes.h \
 ../ltk/LTKScrollingCanvas.h ../ltk/LTKWidget.h Object.h Array.h \
 Dict.h Stream.h GfxState.h GfxFont.h Error.h Params.h TextOutputDev.h \
 OutputDev.h XOutputDev.h config.h \
 XOutputFontInfo.h
XRef.o: XRef.cc \
 ../goo/gmem.h \
 Object.h ../goo/gtypes.h ../goo/GString.h \
 Array.h Dict.h Stream.h Lexer.h Parser.h Error.h XRef.h
xpdf.o: xpdf.cc \
 ../goo/gtypes.h ../goo/GString.h ../goo/parseargs.h ../goo/gfile.h \
 ../goo/gmem.h \
 ../ltk/LTKAll.h ../ltk/LTKApp.h \
 ../ltk/LTKWindow.h ../ltk/LTKMenu.h ../ltk/LTKWidget.h \
 ../ltk/LTKCompoundWidget.h ../ltk/LTKBox.h ../ltk/LTKBorder.h \
 ../ltk/LTKButtonDialog.h ../ltk/LTKButton.h ../ltk/LTKCanvas.h \
 ../ltk/LTKDblBufCanvas.h ../ltk/LTKEmpty.h ../ltk/LTKFileReq.h \
 ../ltk/LTKLabel.h ../ltk/LTKList.h ../ltk/LTKScrollbar.h \
 ../ltk/LTKScrollingCanvas.h ../ltk/LTKTextIn.h ../ltk/LTKResources.h \
 Object.h Array.h Dict.h Stream.h \
 XRef.h Catalog.h Page.h Link.h PDFDoc.h XOutputDev.h config.h \
 OutputDev.h PSOutputDev.h TextOutputDev.h Params.h Error.h \
 xpdfIcon.xpm leftArrow.xbm dblLeftArrow.xbm rightArrow.xbm \
 dblRightArrow.xbm zoomIn.xbm zoomOut.xbm find.xbm postscript.xbm \
 about.xbm xpdf-ltk.h
pdftops.o: pdftops.cc \
 ../goo/parseargs.h ../goo/gtypes.h ../goo/GString.h ../goo/gmem.h \
 Object.h Array.h Dict.h Stream.h XRef.h Catalog.h Page.h PDFDoc.h \
 Link.h PSOutputDev.h config.h OutputDev.h Params.h Error.h
pdftotext.o: pdftotext.cc \
 ../goo/parseargs.h ../goo/gtypes.h ../goo/GString.h ../goo/gmem.h \
 Object.h Array.h Dict.h Stream.h XRef.h Catalog.h Page.h PDFDoc.h \
 Link.h TextOutputDev.h OutputDev.h Params.h Error.h config.h
