// This file was generated by ltkbuild 0.1

LTKWindow *makeWindow(LTKApp *app) {
  return new LTKWindow(app, gFalse, "xpdf",
    new LTKBox(NULL, 1, 2, 0, 0, 0, 0, ltkBorderNone, 1, 1,
      new LTKBox(NULL, 2, 2, 0, 0, 0, 0, ltkBorderNone, 1, 1,
        new LTKBox(NULL, 1, 1, 2, 2, 2, 2, ltkBorderSunken, 1, 1,
          new LTKScrollingCanvas("canvas", 0, 100, 100, 32, 32)
        ),
        new LTKBox(NULL, 1, 1, 2, 2, 2, 2, ltkBorderNone, 0, 1,
          new LTKScrollbar("vScrollbar", 0, gTrue, 0, 100, &scrollVertCbk)
        ),
        new LTKBox(NULL, 1, 1, 2, 2, 2, 2, ltkBorderNone, 1, 0,
          new LTKScrollbar("hScrollbar", 0, gFalse, 0, 100, &scrollHorizCbk)
        ),
        new LTKBox(NULL, 1, 1, 2, 2, 2, 2, ltkBorderNone, 0, 0,
          new LTKEmpty()
        )
      ),
      new LTKBox(NULL, 16, 1, 0, 0, 0, 0, ltkBorderNone, 1, 0,
        new LTKBox(NULL, 1, 1, 2, 2, 2, 2, ltkBorderNone, 0, 0,
          new LTKButton(NULL, 0, dblLeftArrow_bits, dblLeftArrow_width, dblLeftArrow_height, ltkButtonClick, &prevTenPageCbk)
        ),
        new LTKBox(NULL, 1, 1, 2, 2, 2, 2, ltkBorderNone, 0, 0,
          new LTKButton(NULL, 0, leftArrow_bits, leftArrow_width, leftArrow_height, ltkButtonClick, &prevPageCbk)
        ),
        new LTKBox(NULL, 1, 1, 2, 2, 2, 2, ltkBorderNone, 0, 0,
          new LTKButton(NULL, 0, rightArrow_bits, rightArrow_width, rightArrow_height, ltkButtonClick, &nextPageCbk)
        ),
        new LTKBox(NULL, 1, 1, 2, 2, 2, 2, ltkBorderNone, 0, 0,
          new LTKButton(NULL, 0, dblRightArrow_bits, dblRightArrow_width, dblRightArrow_height, ltkButtonClick, &nextTenPageCbk)
        ),
        new LTKBox(NULL, 1, 1, 2, 2, 2, 2, ltkBorderNone, 0, 0,
          new LTKLabel(NULL, 0, -1, "-*-courier-medium-r-*-*-14-*-*-*-*-*-*-*", "Page")
        ),
        new LTKBox(NULL, 1, 1, 4, 4, 2, 2, ltkBorderSunken, 0, 0,
          new LTKTextIn("pageNum", 0, 6, "-*-courier-medium-r-*-*-14-*-*-*-*-*-*-*", &pageNumCbk, NULL)
        ),
        new LTKBox(NULL, 1, 1, 2, 2, 2, 2, ltkBorderNone, 0, 0,
          new LTKLabel("numPages", 0, 9, "-*-courier-medium-r-*-*-14-*-*-*-*-*-*-*", NULL)
        ),
        new LTKBox(NULL, 1, 1, 2, 2, 2, 2, ltkBorderNone, 0, 0,
          new LTKButton(NULL, 0, zoomIn_bits, zoomIn_width, zoomIn_height, ltkButtonClick, &zoomInCbk)
        ),
        new LTKBox(NULL, 1, 1, 2, 2, 2, 2, ltkBorderNone, 0, 0,
          new LTKButton(NULL, 0, zoomOut_bits, zoomOut_width, zoomOut_height, ltkButtonClick, &zoomOutCbk)
        ),
        new LTKBox(NULL, 1, 1, 2, 2, 2, 2, ltkBorderNone, 0, 0,
          new LTKButton(NULL, 0, rotateCW_bits, rotateCW_width, rotateCW_height, ltkButtonClick, &rotateCWCbk)
        ),
        new LTKBox(NULL, 1, 1, 2, 2, 2, 2, ltkBorderNone, 0, 0,
          new LTKButton(NULL, 0, rotateCCW_bits, rotateCCW_width, rotateCCW_height, ltkButtonClick, &rotateCCWCbk)
        ),
        new LTKBox(NULL, 1, 1, 2, 2, 2, 2, ltkBorderNone, 1, 0,
          new LTKEmpty()
        ),
        new LTKBox(NULL, 1, 1, 2, 2, 2, 2, ltkBorderNone, 0, 0,
          new LTKButton(NULL, 0, postscript_bits, postscript_width, postscript_height, ltkButtonClick, &postScriptCbk)
        ),
        new LTKBox(NULL, 1, 1, 2, 2, 2, 2, ltkBorderNone, 0, 0,
          new LTKButton(NULL, 0, about_bits, about_width, about_height, ltkButtonClick, &aboutCbk)
        ),
        new LTKBox(NULL, 1, 1, 2, 2, 2, 2, ltkBorderNone, 1, 0,
          new LTKEmpty()
        ),
        new LTKBox(NULL, 1, 1, 2, 2, 2, 2, ltkBorderNone, 0, 0,
          new LTKButton(NULL, 0, "Quit", ltkButtonClick, &quitCbk)
        )
      )
    )
  );
}

LTKWindow *makePostScriptDialog(LTKApp *app) {
  return new LTKWindow(app, gTrue, "xpdf: PostScript output",
    new LTKBox(NULL, 1, 3, 0, 0, 0, 0, ltkBorderNone, 0, 0,
      new LTKBox(NULL, 4, 1, 0, 0, 0, 0, ltkBorderNone, 0, 0,
        new LTKBox(NULL, 1, 1, 2, 2, 2, 2, ltkBorderNone, 0, 0,
          new LTKLabel(NULL, 0, -1, NULL, "Pages:")
        ),
        new LTKBox(NULL, 1, 1, 2, 2, 2, 2, ltkBorderSunken, 0, 0,
          new LTKTextIn("firstPage", 0, 6, "-*-courier-medium-r-*-*-14-*-*-*-*-*-*-*", NULL, "lastPage")
        ),
        new LTKBox(NULL, 1, 1, 2, 2, 2, 2, ltkBorderNone, 0, 0,
          new LTKLabel(NULL, 0, -1, NULL, "to")
        ),
        new LTKBox(NULL, 1, 1, 2, 2, 2, 2, ltkBorderSunken, 0, 0,
          new LTKTextIn("lastPage", 0, 6, "-*-courier-medium-r-*-*-14-*-*-*-*-*-*-*", NULL, "fileName")
        )
      ),
      new LTKBox(NULL, 2, 1, 0, 0, 0, 0, ltkBorderNone, 0, 0,
        new LTKBox(NULL, 1, 1, 2, 2, 2, 2, ltkBorderNone, 0, 0,
          new LTKLabel(NULL, 0, -1, NULL, "File:")
        ),
        new LTKBox(NULL, 1, 1, 2, 2, 2, 2, ltkBorderSunken, 1, 0,
          new LTKTextIn("fileName", 0, 32, "-*-courier-medium-r-*-*-14-*-*-*-*-*-*-*", NULL, NULL)
        )
      ),
      new LTKBox(NULL, 3, 1, 0, 0, 8, 0, ltkBorderNone, 0, 0,
        new LTKBox(NULL, 1, 1, 2, 2, 2, 2, ltkBorderNone, 0, 0,
          new LTKButton(NULL, 1, "Ok", ltkButtonClick, &psButtonCbk)
        ),
        new LTKBox(NULL, 1, 1, 2, 2, 2, 2, ltkBorderNone, 1, 0,
          new LTKEmpty()
        ),
        new LTKBox(NULL, 1, 1, 2, 2, 2, 2, ltkBorderNone, 0, 0,
          new LTKButton(NULL, 0, "Cancel", ltkButtonClick, &psButtonCbk)
        )
      )
    )
  );
}

LTKWindow *makeAboutWindow(LTKApp *app) {
  return new LTKWindow(app, gFalse, "About xpdf",
    new LTKBox(NULL, 1, 2, 0, 0, 0, 0, ltkBorderNone, 0, 0,
      new LTKBox(NULL, 1, 8, 2, 2, 2, 2, ltkBorderSunken, 0, 0,
        new LTKBox(NULL, 1, 1, 2, 2, 2, 0, ltkBorderNone, 0, 0,
          new LTKLabel(NULL, 0, -1, "-*-times-bold-i-*-*-24-*-*-*-*-*-*-*", "xpdf")
        ),
        new LTKBox(NULL, 1, 1, 2, 2, 2, 12, ltkBorderNone, 0, 0,
          new LTKLabel(NULL, 0, -1, NULL, "Version " xpdfVersion)
        ),
        new LTKBox(NULL, 1, 1, 2, 2, 2, 0, ltkBorderNone, 0, 0,
          new LTKLabel(NULL, 0, -1, NULL, xpdfCopyright)
        ),
        new LTKBox(NULL, 1, 1, 2, 2, 2, 12, ltkBorderNone, 0, 0,
          new LTKLabel(NULL, 0, -1, NULL, "derekn@ece.cmu.edu")
        ),
        new LTKBox(NULL, 1, 1, 2, 2, 2, 0, ltkBorderNone, 0, 0,
          new LTKLabel(NULL, 0, -1, NULL, "Supports PDF version " pdfVersion ".")
        ),
        new LTKBox(NULL, 1, 1, 2, 2, 2, 0, ltkBorderNone, 0, 0,
          new LTKLabel(NULL, 0, -1, NULL, "The PDF data structures, operators, and specification")
        ),
        new LTKBox(NULL, 1, 1, 2, 2, 2, 12, ltkBorderNone, 0, 0,
          new LTKLabel(NULL, 0, -1, NULL, "are copyright 1995 Adobe Systems Inc.")
        ),
        new LTKBox(NULL, 1, 1, 2, 2, 2, 12, ltkBorderNone, 0, 0,
          new LTKLabel(NULL, 0, -1, NULL, "http://www.contrib.andrew.cmu.edu/usr/dn0o/xpdf/xpdf.html")
        )
      ),
      new LTKBox(NULL, 2, 1, 0, 0, 0, 0, ltkBorderNone, 0, 0,
        new LTKBox(NULL, 1, 1, 2, 2, 2, 2, ltkBorderNone, 1, 0,
          new LTKEmpty()
        ),
        new LTKBox(NULL, 1, 1, 2, 2, 2, 2, ltkBorderNone, 0, 0,
          new LTKButton(NULL, 0, "Close", ltkButtonClick, &closeAboutCbk)
        )
      )
    )
  );
}

